# .github/workflows/linting.yml

name: Linting and Type Checking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: make install

      - name: Run linter
        # O formatador é executado no modo --check para falhar se o código não estiver formatado.
        run: |
          make format -- --check
          make lint

      - name: Run type checker
        run: make typecheck